### ISSUE TITLE
Problem rendering a nii.gz image

### ISSUE THREAD

**Issue by pyaf** [valette/desk#5]
Hi,

I've installed `libvtk6-dev` on my ubuntu machine, `npm install` ran  well without errors. While running `npm run buildAddons` I got following warning, though it got built successfully.
```bash
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.
```
While running the local server by `node desk.js` and trying to load a nii.gz file (Brain MRI), I'm getting following error in the terminal and the image is not getting rendered on the webpage.

`nice: ‘/media/ags/CODE/GE/test/desk/extensions/addons/ACVD/bin/VolumeSlice’: No such file or directory`

Please help.

**Comment by pyaf** [comment]
Okay, the cause of the error was that `desk` source code was not in my home directory. Still, when I try to load a .nii.gz file I don't see any rendering and there's no error in terminal logs

**Comment by valette** [comment]
Nice catch! Forgot to push changes to public git repo for reading nii files.
commit valette/ACVD@d01dfdcb56d3d52659c9cf8f5bc0b852cf67ec32 should do it
please relaunch buildAddons, does it work on your side now?

**Comment by pyaf** [comment]
Yup, works now.
Just had one question, can I load segmentation image over to my scan image (both are in nii format)?
